name: notifoo
description: Stheer - An app to correct phone addiction and converting a person into a better focussed human individual.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.17.0

  # Database
  sqflite: ^2.0.2
  path: ^1.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0


  # Google Sign in
  firebase_auth: ^4.2.6
  google_sign_in: ^5.2.4

  #Notifications
  flutter_notification_listener: ^1.0.7
  #clear_all_notifications: ^0.0.2 
  eraser: ^2.0.1
  timeago: ^3.2.2

  collection: ^1.15.0
  device_apps: ^2.2.0
  dio: ^5.0.1
  percent_indicator: ^4.2.3


  flutter_slidable: ^2.0.0
  flutter_heatmap_calendar: ^1.0.5
  #fonts
  google_fonts: ^4.0.3

  # Google Icons
  font_awesome_flutter: ^10.4.0

  # State Management
  provider: ^6.0.2

 



    # When depending on this package from a real application you should use:
    #   flutter_notification_listener: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    #path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

#splash screen package and configuration
  flutter_native_splash: ^2.1.0

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android: true
  ios: false
  android_gravity: center
  #ios_content_mode: center
  fullscreen: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/welcome-one.png
  #- images/
      # - assets/fonts/Raleway-Regular.ttf
      # - assets/fonts/Raleway-Thin.ttf
     
  #  - assets/images/
  #  - assets/images/welcome-three.png
  #  - assets/images/splash_image.png


fonts:
  - family: Raleway-Regular
    fonts:
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Thin.ttf
        style: normal
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
