name: notifoo
description: FocusFluke - A modern notification management app that helps you batch and read notifications later, improving focus and productivity.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1

  # Database
  sqflite: ^2.0.2
  path: ^1.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Google Sign in
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^5.2.4

  # Firebase Firestore
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.2.6

  # Notifications (native implementation replaces plugin)
  # flutter_notification_listener: ^1.3.4
  #clear_all_notifications: ^0.0.2 
  #eraser: ^2.0.1
  timeago: ^3.2.2

  collection: ^1.15.0
  # device_apps is discontinued and incompatible with latest AGP; temporarily removed to unblock build
  # device_apps: ^2.2.0
  dio: ^5.0.1
  percent_indicator: ^4.2.3
  confetti: ^0.7.0
  flutter_iconpicker: ^3.4.4

  flutter_slidable: ^3.0.1
  flutter_heatmap_calendar: ^1.0.5
  fl_heatmap: ^0.2.0
  
  #fonts
  google_fonts: ^4.0.3

  # Google Icons
  font_awesome_flutter: ^10.4.0

  # State Management
  provider: ^6.0.2

  # URL Launcher
  url_launcher: ^6.1.14

  # HTTP Client
  http: ^1.1.0

  # App Settings
  app_settings: ^5.1.1

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Push Notifications
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

  # File Operations & Sharing
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  
  # Enhanced UI Components
  flutter_staggered_animations: ^1.1.1
  lottie: ^2.7.0
  shimmer: ^3.0.0
  
  # Widget Support (newer version compatible with recent Flutter)
  home_widget: ^0.8.0
  
  # Voice Commands
  speech_to_text: ^6.6.0
  geolocator: ^9.0.2
  
  # Calendar Integration
  device_calendar: ^4.3.3

  # Payment & Subscription Management
  in_app_purchase: ^3.1.11
  in_app_purchase_android: ^0.3.6+1
  in_app_purchase_storekit: ^0.3.6+1

    # When depending on this package from a real application you should use:
    #   flutter_notification_listener: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    #path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

#splash screen package and configuration
  flutter_native_splash: ^2.1.0

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android: true
  ios: false
  android_gravity: center
  #ios_content_mode: center
  fullscreen: true

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/welcome-one.png
  #- images/
      # - assets/fonts/Raleway-Regular.ttf
      # - assets/fonts/Raleway-Thin.ttf
     
  #  - assets/images/
  #  - assets/images/welcome-three.png
  #  - assets/images/splash_image.png


fonts:
  - family: Raleway-Regular
    fonts:
      - asset: fonts/Raleway-Regular.ttf
      - asset: fonts/Raleway-Thin.ttf
        style: normal
    
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
